---
version: '3.1'
services:
  mkcert:
    image: ghcr.io/tenzin-io/mkcert:amd64-v1
    environment:
      - 'CERT_HOSTNAME=confluence'
      - 'CERT_DOMAIN=tenzin.io'
    volumes:
      - certs_data:/certs.d

  confluence:
    environment:
      - TZ=America/New_York
      - JVM_MAXIMUM_MEMORY=8192m
      - CONFLUENCE_HOME=/confluence_data
      - ATL_PROXY_NAME=confluence.tenzin.io
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_SCHEME=https
    build: 
      context: ./build-confluence
    restart: unless-stopped
    volumes:
      - confluence_data:/confluence_data

  nginx:
    build:
      context: ./build-nginx
    restart: unless-stopped
    depends_on:
      - confluence
      - mkcert
    environment:
      - TZ=America/New_York
    restart: unless-stopped
    volumes:
      - certs_data:/etc/nginx/certs.d/
    ports:
      - 443:443

volumes:
  confluence_data:
  certs_data: 
